namespace NonboxingUnion.Generator.CodeGeneration;

internal static class CodeSnippets
{
    public static string NonBoxingUnionFileHeader => """
// <auto-generated/>
#nullable enable
#pragma warning disable CA1815 // Override equals and operator equals on value types

""";
}
