namespace NonboxingUnion.Generator.CodeGeneration;

internal static class CodeSnippets
{
    public static string NonBoxingUnionFileHeader => """
// <auto-generated/>
#nullable enable
#pragma warning disable CA1815 // Override equals and operator equals on value types

""";

    /// <summary>
    /// The source for the marker attribute when it is embedded directly into the
    /// consumer's compilation rather than supplied by a referenced runtime assembly.
    /// </summary>
    /// <remarks>
    /// The type is <c>internal</c> and annotated with
    /// <c>[Microsoft.CodeAnalysis.EmbeddedAttribute]</c> so that it is scoped to the
    /// compilation it is generated into. This is what lets the same attribute be
    /// emitted across many projects (including ones connected via
    /// <c>[InternalsVisibleTo]</c>) without producing <c>CS0436</c> conflicts.
    /// The metadata name (<c>NonboxingUnion.NonBoxingUnionAttribute</c>) and shape
    /// match the public attribute shipped in the runtime package, so user code and
    /// the generator behave identically in both modes.
    /// </remarks>
    public static string EmbeddedMarkerAttribute(string toolName, string? toolVersion) => $$"""
// <auto-generated/>
#nullable enable

namespace NonboxingUnion
{
    /// <summary>
    /// Marks a partial struct as a non-boxing discriminated union for which the
    /// source generator will emit the discriminator, per-variant storage, and the
    /// union access members as well as a constructor for each case type.
    /// </summary>
    [global::Microsoft.CodeAnalysis.EmbeddedAttribute]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("{{toolName}}", "{{toolVersion}}")]
    [global::System.AttributeUsage(global::System.AttributeTargets.Struct, AllowMultiple = false, Inherited = false)]
    internal sealed class NonBoxingUnionAttribute : global::System.Attribute
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NonBoxingUnionAttribute"/> class.
        /// </summary>
        /// <param name="types">The case types (variants) that make up the union.</param>
        public NonBoxingUnionAttribute(params global::System.Type[] types)
        {
            Types = types;
        }

        /// <summary>
        /// Gets the case types (variants) that make up the union.
        /// </summary>
        public global::System.Type[] Types { get; }
    }
}

""";
}
